name: adventofcode2016
version: 0.0.1
description: solutions for http://adventofcode.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  resource: any
  logging: any
  crypto: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
